<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductSpecification;
use App\Models\Category;
use App\Models\Brand;

class TrendingProductsSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'smart-phones' => Category::where('slug', 'smart-phones')->firstOrFail()->id,
            'computer-laptop' => Category::where('slug', 'computer-laptop')->firstOrFail()->id,
            'digital-cameras' => Category::where('slug', 'digital-cameras')->firstOrFail()->id,
            'audio' => Category::where('slug', 'audio')->firstOrFail()->id,
        ];

        $brand = Brand::firstOrCreate(
            ['slug' => 'apple'],
            ['name' => 'Apple', 'is_active' => true]
        );

        $products = [
            [
                'name' => 'Trending: Apple iPhone 15 Pro Max 256GB',
                'category_id' => $categories['smart-phones'] ?? 4,
                'brand_id' => $brand->id,
                'price' => 1199.99,
                'old_price' => 1299.99,
                'quantity' => 30,
                'short_description' => 'Premium smartphone with A17 Pro chip, titanium design, and advanced camera system.',
                'description' => '<p>The Apple iPhone 15 Pro Max features a stunning titanium design, the powerful A17 Pro chip, and a pro camera system that takes your photography to the next level. With a 6.7-inch Super Retina XDR display and up to 1TB of storage, this is the most advanced iPhone ever.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-1.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-1.jpg',
                    'assets/images/demos/demo-4/products/product-2.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '6.7 inches Super Retina XDR'],
                    ['key' => 'Processor', 'value' => 'A17 Pro chip'],
                    ['key' => 'Storage', 'value' => '256GB'],
                    ['key' => 'Camera', 'value' => '48MP Main + 12MP Ultra Wide'],
                ],
                'sku' => 'TREND-IPHONE-001',
                'is_active' => true,
                'is_trending' => true,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 1,
            ],
            [
                'name' => 'Trending: Apple MacBook Pro 14-inch M3 Pro',
                'category_id' => $categories['computer-laptop'] ?? 1,
                'brand_id' => $brand->id,
                'price' => 1999.99,
                'old_price' => 2199.99,
                'quantity' => 15,
                'short_description' => 'Supercharged by M3 Pro chip for extreme performance.',
                'description' => '<p>The MacBook Pro 14-inch with M3 Pro chip delivers exceptional performance for demanding workflows. Featuring a stunning Liquid Retina XDR display, up to 18 hours of battery life, and a comprehensive array of ports.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-11.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-11.jpg',
                    'assets/images/demos/demo-4/products/product-12.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '14.2 inches Liquid Retina XDR'],
                    ['key' => 'Processor', 'value' => 'M3 Pro chip'],
                    ['key' => 'RAM', 'value' => '18GB'],
                    ['key' => 'Storage', 'value' => '512GB SSD'],
                ],
                'sku' => 'TREND-MBP-001',
                'is_active' => true,
                'is_trending' => true,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 2,
            ],
            [
                'name' => 'Top Rated: Sony Alpha a7 IV Mirrorless Camera',
                'category_id' => $categories['digital-cameras'] ?? 3,
                'brand_id' => $brand->id,
                'price' => 2499.99,
                'old_price' => 2699.99,
                'quantity' => 8,
                'short_description' => 'Full-frame mirrorless camera with 33MP sensor and 4K 60p video.',
                'description' => '<p>The Sony Alpha a7 IV is a full-frame mirrorless camera that combines a 33MP Exmor R CMOS sensor with the powerful BIONZ XR processor. It offers exceptional image quality, fast autofocus, and professional-grade video capabilities.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-13.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-13.jpg',
                    'assets/images/demos/demo-4/products/product-14.jpg',
                ],
                'specifications' => [
                    ['key' => 'Sensor', 'value' => '33MP Full-Frame Exmor R'],
                    ['key' => 'Video', 'value' => '4K 60p'],
                    ['key' => 'ISO', 'value' => '100-51200'],
                    ['key' => 'Weight', 'value' => '658g'],
                ],
                'sku' => 'TOP-SONY-A7IV',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => true,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 3,
            ],
            [
                'name' => 'Top Rated: Bose QuietComfort Ultra Headphones',
                'category_id' => $categories['audio'] ?? 6,
                'brand_id' => $brand->id,
                'price' => 429.99,
                'old_price' => 479.99,
                'quantity' => 25,
                'short_description' => 'World-class noise cancelling headphones with immersive audio.',
                'description' => '<p>The Bose QuietComfort Ultra headphones deliver world-class noise cancellation and immersive spatial audio. With luxurious comfort and a 24-hour battery life, they are perfect for travel, work, and everyday listening.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-6.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-6.jpg',
                    'assets/images/demos/demo-4/products/product-7.jpg',
                ],
                'specifications' => [
                    ['key' => 'Type', 'value' => 'Over-ear'],
                    ['key' => 'Connectivity', 'value' => 'Bluetooth 5.3'],
                    ['key' => 'Battery Life', 'value' => '24 hours'],
                    ['key' => 'Noise Cancelling', 'value' => 'Yes'],
                ],
                'sku' => 'TOP-BOSE-QC',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => true,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 4,
            ],
            [
                'name' => 'Best Selling: Samsung Galaxy S24 Ultra 512GB',
                'category_id' => $categories['smart-phones'] ?? 4,
                'brand_id' => $brand->id,
                'price' => 1299.99,
                'old_price' => 1399.99,
                'quantity' => 50,
                'short_description' => 'Ultimate Galaxy experience with AI-powered features and S Pen.',
                'description' => '<p>The Samsung Galaxy S24 Ultra is the ultimate smartphone with a powerful Snapdragon 8 Gen 3 processor, a 200MP camera, and a built-in S Pen. With Galaxy AI, you can translate, search, and create like never before.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-3.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-3.jpg',
                    'assets/images/demos/demo-4/products/product-4.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '6.8 inches Dynamic AMOLED'],
                    ['key' => 'Processor', 'value' => 'Snapdragon 8 Gen 3'],
                    ['key' => 'Storage', 'value' => '512GB'],
                    ['key' => 'Camera', 'value' => '200MP Main + 50MP Zoom'],
                ],
                'sku' => 'BEST-SAM-S24U',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => true,
                'is_on_sale' => false,
                'display_order' => 5,
            ],
            [
                'name' => 'Best Selling: Apple iPad Air 5th Gen 256GB',
                'category_id' => $categories['computer-laptop'] ?? 1,
                'brand_id' => $brand->id,
                'price' => 749.99,
                'old_price' => 799.99,
                'quantity' => 35,
                'short_description' => 'Supercharged by M1 chip for all-day performance.',
                'description' => '<p>The iPad Air 5th generation is powered by the M1 chip, delivering incredible performance for creative work, gaming, and everyday tasks. With a 10.9-inch Liquid Retina display and support for Apple Pencil and Magic Keyboard.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-10.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-10.jpg',
                    'assets/images/demos/demo-4/products/product-11.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '10.9 inches Liquid Retina'],
                    ['key' => 'Processor', 'value' => 'M1 chip'],
                    ['key' => 'Storage', 'value' => '256GB'],
                    ['key' => 'Weight', 'value' => '461g'],
                ],
                'sku' => 'BEST-IPAD-AIR',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => true,
                'is_on_sale' => false,
                'display_order' => 6,
            ],
            [
                'name' => 'On Sale: Google Pixel 8 Pro 128GB',
                'category_id' => $categories['smart-phones'] ?? 4,
                'brand_id' => $brand->id,
                'price' => 799.99,
                'old_price' => 999.99,
                'quantity' => 20,
                'short_description' => 'Google AI phone with advanced camera and Tensor G3 chip.',
                'description' => '<p>The Google Pixel 8 Pro features the powerful Tensor G3 chip, an advanced triple camera system, and Google AI that helps you do more with your phone. With a 6.7-inch Super Actua display and 7 years of OS updates.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-4.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-4.jpg',
                    'assets/images/demos/demo-4/products/product-5.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '6.7 inches Super Actua OLED'],
                    ['key' => 'Processor', 'value' => 'Google Tensor G3'],
                    ['key' => 'Storage', 'value' => '128GB'],
                    ['key' => 'Camera', 'value' => '50MP Main + 48MP Telephoto'],
                ],
                'sku' => 'SALE-PIXEL-8P',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'On Sale: Canon EOS R6 Mark II Mirrorless',
                'category_id' => $categories['digital-cameras'] ?? 3,
                'brand_id' => $brand->id,
                'price' => 2299.99,
                'old_price' => 2499.99,
                'quantity' => 12,
                'short_description' => 'Full-frame mirrorless with 24.2MP sensor and 4K 60p video.',
                'description' => '<p>The Canon EOS R6 Mark II is a powerful full-frame mirrorless camera with a 24.2MP CMOS sensor, DIGIC X processor, and up to 40fps continuous shooting. Perfect for sports, wildlife, and portrait photography.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-9.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-9.jpg',
                    'assets/images/demos/demo-4/products/product-8.jpg',
                ],
                'specifications' => [
                    ['key' => 'Sensor', 'value' => '24.2MP Full-Frame CMOS'],
                    ['key' => 'Video', 'value' => '4K 60p'],
                    ['key' => 'ISO', 'value' => '100-102400'],
                    ['key' => 'Weight', 'value' => '588g'],
                ],
                'sku' => 'SALE-CANON-R6',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => true,
                'display_order' => 8,
            ],
            [
                'name' => 'Trending: Samsung Galaxy Z Flip 6',
                'category_id' => $categories['smart-phones'] ?? 4,
                'brand_id' => $brand->id,
                'price' => 999.99,
                'old_price' => 1099.99,
                'quantity' => 18,
                'short_description' => 'Foldable smartphone with Flex Mode and vibrant display.',
                'description' => '<p>The Samsung Galaxy Z Flip 6 brings the iconic foldable design to the next level with a larger cover screen, improved hinge, and Snapdragon 8 Gen 3 performance. Perfect for multitasking and style.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-2.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-2.jpg',
                    'assets/images/demos/demo-4/products/product-1.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '6.7 inches Foldable AMOLED'],
                    ['key' => 'Processor', 'value' => 'Snapdragon 8 Gen 3'],
                    ['key' => 'Storage', 'value' => '256GB'],
                    ['key' => 'Weight', 'value' => '187g'],
                ],
                'sku' => 'TREND-ZFLIP6',
                'is_active' => true,
                'is_trending' => true,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 9,
            ],
            [
                'name' => 'Trending: Dell XPS 16 9640',
                'category_id' => $categories['computer-laptop'] ?? 1,
                'brand_id' => $brand->id,
                'price' => 1499.99,
                'old_price' => 1649.99,
                'quantity' => 22,
                'short_description' => 'Stunning 16-inch Windows laptop with Intel Core Ultra and OLED display.',
                'description' => '<p>The Dell XPS 16 9640 combines a beautiful 16.3-inch OLED display with Intel Core Ultra processors and a sleek, borderless design. Ideal for creators and professionals.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-12.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-12.jpg',
                    'assets/images/demos/demo-4/products/product-11.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '16.3 inches OLED'],
                    ['key' => 'Processor', 'value' => 'Intel Core Ultra 7'],
                    ['key' => 'RAM', 'value' => '16GB'],
                    ['key' => 'Storage', 'value' => '512GB SSD'],
                ],
                'sku' => 'TREND-DELL-XPS16',
                'is_active' => true,
                'is_trending' => true,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 10,
            ],
            [
                'name' => 'Top Rated: Apple AirPods Pro 2nd Gen',
                'category_id' => $categories['audio'] ?? 6,
                'brand_id' => $brand->id,
                'price' => 229.99,
                'old_price' => 249.99,
                'quantity' => 60,
                'short_description' => 'Active Noise Cancellation, Adaptive Transparency, and personalized Spatial Audio.',
                'description' => '<p>AirPods Pro 2nd generation deliver up to 2x more Active Noise Cancellation, Adaptive Transparency, and a personalized Spatial Audio experience. With a new low-distortion driver and improved battery life.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-7.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-7.jpg',
                    'assets/images/demos/demo-4/products/product-6.jpg',
                ],
                'specifications' => [
                    ['key' => 'Type', 'value' => 'In-ear'],
                    ['key' => 'Connectivity', 'value' => 'Bluetooth 5.3'},
                    ['key' => 'Battery Life', 'value' => 'Up to 6 hours'},
                    ['key' => 'Noise Cancelling', 'value' => 'Yes'},
                ],
                'sku' => 'TOP-AIRPODS-PRO2',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => true,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 11,
            ],
            [
                'name' => 'Top Rated: Sony WF-1000XM5 Earbuds',
                'category_id' => $categories['audio'] ?? 6,
                'brand_id' => $brand->id,
                'price' => 299.99,
                'old_price' => 329.99,
                'quantity' => 35,
                'short_description' => 'Industry-leading noise canceling truly wireless earbuds.',
                'description' => '<p>Sony WF-1000XM5 earbuds feature the latest noise canceling technology, a compact design, and rich, detailed sound. Perfect for music lovers and commuters.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-6.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-6.jpg',
                    'assets/images/demos/demo-4/products/product-7.jpg',
                ],
                'specifications' => [
                    ['key' => 'Type', 'value' => 'In-ear'},
                    ['key' => 'Connectivity', 'value' => 'Bluetooth 5.3'},
                    ['key' => 'Battery Life', 'value' => 'Up to 8 hours'},
                    ['key' => 'Noise Cancelling', 'value' => 'Yes'},
                ],
                'sku' => 'TOP-SONY-XM5',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => true,
                'is_best_selling' => false,
                'is_on_sale' => false,
                'display_order' => 12,
            ],
            [
                'name' => 'Best Selling: Apple Watch Series 9 45mm',
                'category_id' => $categories['smart-phones'] ?? 4,
                'brand_id' => $brand->id,
                'price' => 399.99,
                'old_price' => 429.99,
                'quantity' => 45,
                'short_description' => 'Advanced health features and bright display.',
                'description' => '<p>Apple Watch Series 9 features a brighter display, advanced health sensors, and the powerful S9 chip. Track your fitness, stay connected, and take control of your health.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-5.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-5.jpg',
                    'assets/images/demos/demo-4/products/product-9.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '45mm Retina LTPO OLED'},
                    ['key' => 'Processor', 'value' => 'S9 SiP'},
                    ['key' => 'Storage', 'value' => '64GB'},
                    ['key' => 'Battery', 'value' => 'Up to 18 hours'},
                ],
                'sku' => 'BEST-AW-S9',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => true,
                'is_on_sale' => false,
                'display_order' => 13,
            ],
            [
                'name' => 'Best Selling: Samsung Galaxy Tab S9 Ultra',
                'category_id' => $categories['computer-laptop'] ?? 1,
                'brand_id' => $brand->id,
                'price' => 1099.99,
                'old_price' => 1199.99,
                'quantity' => 28,
                'short_description' => '14.6-inch Dynamic AMOLED tablet with S Pen.',
                'description' => '<p>The Samsung Galaxy Tab S9 Ultra is the ultimate Android tablet with a massive 14.6-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, and included S Pen for creativity and productivity.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-10.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-10.jpg',
                    'assets/images/demos/demo-4/products/product-11.jpg',
                ],
                'specifications' => [
                    ['key' => 'Display', 'value' => '14.6 inches Dynamic AMOLED'},
                    ['key' => 'Processor', 'value' => 'Snapdragon 8 Gen 2'},
                    ['key' => 'Storage', 'value' => '256GB'},
                    ['key' => 'Weight', 'value' => '732g'},
                ],
                'sku' => 'BEST-TAB-S9U',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => true,
                'is_on_sale' => false,
                'display_order' => 14,
            ],
            [
                'name' => 'On Sale: Sony Alpha ZV-E10 II Mirrorless',
                'category_id' => $categories['digital-cameras'] ?? 3,
                'brand_id' => $brand->id,
                'price' => 699.99,
                'old_price' => 799.99,
                'quantity' => 20,
                'short_description' => 'Compact mirrorless camera built for vlogging.',
                'description' => '<p>The Sony ZV-E10 II is designed for content creators with a flip-out screen, directional microphone, and the powerful E-mount lens system. Capture stunning photos and videos easily.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-13.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-13.jpg',
                    'assets/images/demos/demo-4/products/product-14.jpg',
                ],
                'specifications' => [
                    ['key' => 'Sensor', 'value' => '26MP APS-C'},
                    ['key' => 'Video', 'value' => '4K 60p'},
                    ['key' => 'Weight', 'value' => '292g'},
                    ['key' => 'Battery', 'value' => 'Up to 520 shots'},
                ],
                'sku' => 'SALE-SONY-ZVE10',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => true,
                'display_order' => 15,
            ],
            [
                'name' => 'On Sale: Bose SoundLink Max Speaker',
                'category_id' => $categories['audio'] ?? 6,
                'brand_id' => $brand->id,
                'price' => 329.99,
                'old_price' => 379.99,
                'quantity' => 25,
                'short_description' => 'Portable Bluetooth speaker with deep bass.',
                'description' => '<p>The Bose SoundLink Max delivers room-filling sound with deep, accurate bass. Durable, water-resistant, and perfect for outdoor adventures.</p>',
                'shipping_information' => 'Free standard shipping on all orders over $50. Orders are typically processed within 1-2 business days.',
                'return_policy' => 'We offer a 30-day return policy for all unused items in original packaging.',
                'image' => 'assets/images/demos/demo-4/products/product-7.jpg',
                'gallery' => [
                    'assets/images/demos/demo-4/products/product-7.jpg',
                    'assets/images/demos/demo-4/products/product-6.jpg',
                ],
                'specifications' => [
                    ['key' => 'Type', 'value' => 'Portable Speaker'},
                    ['key' => 'Connectivity', 'value' => 'Bluetooth 5.3'},
                    ['key' => 'Battery Life', 'value' => 'Up to 20 hours'},
                    ['key' => 'Water Resistant', 'value' => 'Yes'},
                ],
                'sku' => 'SALE-BOSE-SLMAX',
                'is_active' => true,
                'is_trending' => false,
                'is_top_rated' => false,
                'is_best_selling' => false,
                'is_on_sale' => true,
                'display_order' => 16,
            ],
        ];

        foreach ($products as $data) {
            $product = Product::updateOrCreate(
                ['sku' => $data['sku']],
                [
                    'name' => $data['name'],
                    'slug' => null,
                    'category_id' => $data['category_id'],
                    'brand_id' => $data['brand_id'],
                    'price' => $data['price'],
                    'old_price' => $data['old_price'],
                    'quantity' => $data['quantity'],
                    'short_description' => $data['short_description'],
                    'description' => $data['description'],
                    'shipping_information' => $data['shipping_information'],
                    'return_policy' => $data['return_policy'],
                    'image' => $data['image'],
                    'sku' => $data['sku'],
                    'is_active' => $data['is_active'],
                    'is_trending' => $data['is_trending'],
                    'is_top_rated' => $data['is_top_rated'],
                    'is_best_selling' => $data['is_best_selling'],
                    'is_on_sale' => $data['is_on_sale'],
                    'display_order' => $data['display_order'],
                ]
            );

            $product->images()->delete();
            $product->specifications()->delete();

            foreach ($data['gallery'] as $galleryIndex => $galleryImage) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image' => $galleryImage,
                    'order' => $galleryIndex + 1,
                ]);
            }

            foreach ($data['specifications'] as $specIndex => $spec) {
                ProductSpecification::create([
                    'product_id' => $product->id,
                    'key' => $spec['key'],
                    'value' => $spec['value'],
                    'order' => $specIndex + 1,
                ]);
            }
        }
    }
}
